font_family monospace
font_size 11.0
background #0b1626
foreground #dce7f7
cursor #88bdff
selection_background #29435f
selection_foreground #ffffff
window_padding_width 14
confirm_os_window_close -1
enable_audio_bell no
